# SPDX-License-Identifier: GPL-3.0-only

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI for Zerotier
LUCI_DEPENDS:=+zerotier +curl
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-zerotier
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature


